import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import TextField from "@mui/material/TextField";
import MenuItem from "@mui/material/MenuItem";
import DateRangePicker from "@mui/lab/DateRangePicker";
import AdapterDateFns from "@mui/lab/AdapterDateFns";
import LocalizationProvider from "@mui/lab/LocalizationProvider";
import { useState } from "react";
import DatePicker from "@mui/lab/DatePicker";
import Button from "@mui/material/Button";

const DEPARTMENTS = [
  {
    value: "ENG",
    label: "Engineering",
  },
  {
    value: "DES",
    label: "Design",
  },
  {
    value: "ADM",
    label: "Admin",
  },
];

export default function Home() {
  const [department, setDepartment] = useState("Engineering");
  const [value, setValue] = useState([null, null]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Leave Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Proximity Leave Application</h1>
        <div className={styles.wrapper}>
          <form className={styles.form}>
            <div className={styles.formInput}>
              <TextField id="standard-basic" label="Name" variant="standard" />
            </div>
            <div className={styles.formInput}>
              <TextField
                select
                value={department}
                helperText="Please select your Department"
                variant="standard"
              >
                {DEPARTMENTS.map((option) => (
                  <MenuItem key={option.value} value={option.value}>
                    {option.label}
                  </MenuItem>
                ))}
              </TextField>
            </div>
            <div className={styles.formDates}>
              <div className={styles.formInput}>
                <LocalizationProvider dateAdapter={AdapterDateFns}>
                  <DatePicker
                    label="From Date"
                    value={value}
                    onChange={(newValue) => {
                      setValue(newValue);
                    }}
                    renderInput={(params) => <TextField {...params} />}
                  />
                </LocalizationProvider>
              </div>
              <div className={styles.formInput}>
                <LocalizationProvider dateAdapter={AdapterDateFns}>
                  <DatePicker
                    label="To Date"
                    value={value}
                    onChange={(newValue) => {
                      setValue(newValue);
                    }}
                    renderInput={(params) => <TextField {...params} />}
                  />
                </LocalizationProvider>
              </div>
            </div>
            <div className={styles.formInput}>
              <TextField
                id="standard-textarea"
                label="Reason"
                placeholder="Ex. Fever, Personal Work"
                multiline
                variant="standard"
              />
            </div>
            <div>
              <Button variant="contained">Submit</Button>
            </div>
          </form>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
